### ISSUE TITLE
Crit-a-Cola model loads Bonk! Atomic Punch textures 

### ISSUE THREAD

**Issue by As0mn** [neodoso/TFMV#3]
When loading the Crit-a-Cola, TFMV uses the Bonk! Atomic Punch textures instead of the Crit-a-Cola textures. This is because TFMV is loading `c_energydrink.vmt` instead of  `c_energydrink_purp.vmt`.
![image](https://user-images.githubusercontent.com/109611240/227370999-7e4f7883-7a6a-4a14-aedc-9d93d1370834.png)

**Comment by neodoso** [comment]
I am no longer working on TFMV, please ask Neodement here: https://github.com/NeoDement/TFMV
